# Generated by Django 2.2.12 on 2020-05-26 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        ('topic', '0002_auto_20200526_1438'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=50, verbose_name='content')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='created time')),
                ('parent_message', models.IntegerField(default=0, verbose_name='parent message')),
                ('publisher_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user_profile', verbose_name='id of publisher')),
                ('topic_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='topic.Topic', verbose_name='id of topic')),
            ],
            options={
                'db_table': 'message',
            },
        ),
    ]
