# Generated by Django 2.2.12 on 2020-05-23 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='artical title')),
                ('category', models.CharField(max_length=20, verbose_name='category of blog')),
                ('limit', models.CharField(max_length=10, verbose_name='reading limit')),
                ('introduce', models.CharField(max_length=90, verbose_name='introduce of artical')),
                ('content', models.TextField(verbose_name='content of artical')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='creating time of artical')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='updating time of artical')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user_profile')),
            ],
            options={
                'db_table': 'topic',
            },
        ),
    ]
