# Generated by Django 2.2.12 on 2020-05-26 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='content',
            field=models.TextField(verbose_name='content of article'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='creating time of article'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='introduce',
            field=models.CharField(max_length=90, verbose_name='introduce of article'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='title',
            field=models.CharField(max_length=50, verbose_name='article title'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='updated_time',
            field=models.DateTimeField(auto_now=True, verbose_name='updating time of article'),
        ),
    ]
