# Generated by Django 2.2.12 on 2020-05-15 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user_profile',
            fields=[
                ('username', models.CharField(max_length=11, primary_key=True, serialize=False, verbose_name='username')),
                ('nickname', models.CharField(max_length=30, verbose_name='nickname')),
                ('email', models.EmailField(max_length=254, null=True, verbose_name='email')),
                ('password', models.CharField(max_length=32, verbose_name='password')),
                ('sign', models.CharField(max_length=50, verbose_name='personal sign')),
                ('info', models.CharField(max_length=150, verbose_name='presonal description')),
                ('avatar', models.ImageField(upload_to='avatar/')),
            ],
        ),
    ]
