# Generated by Django 2.2.12 on 2020-05-26 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user_profile',
            table='user_profole',
        ),
    ]
